version: "2.1"

services:
    mysql:
        env_file: .env
        image: mysql:5.7
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 10s
            retries: 5
    
    api:
        restart: always
        env_file: .env
        build:
            context: api
            dockerfile: Dockerfile
        expose:
            - "8080"
        links:
            - mysql
        depends_on: 
            mysql:
                condition: service_healthy
    
    web:
        restart: always
        build:
            context: web
            dockerfile: Dockerfile
        links:
            - api
        depends_on:
            - api
        ports:
            - "9090:80"

volumes:
    db_data:
